[package]
name = "shader"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
png = "0.17.16"
rand = "0.9.0"

iced.workspace = true
sipper.workspace = true
bytemuck.workspace = true
sleepy_hollow.workspace = true
